"""
Workflow event handlers and utilities.
"""
from collections.abc import AsyncIterable
from typing import cast

from agent_framework import (
    AgentResponse,
    AgentRunEvent,
    ChatMessage,
    HandoffAgentUserRequest,
    HandoffSentEvent,
    RequestInfoEvent,
    WorkflowEvent,
    WorkflowOutputEvent,
    WorkflowRunState,
    WorkflowStatusEvent,
)


async def drain_events(stream: AsyncIterable[WorkflowEvent]) -> list[WorkflowEvent]:
    """
    Collect all events from an async stream into a list.
    
    This helper drains the workflow's event stream so we can process events
    synchronously after each workflow step completes.
    
    Args:
        stream: Async iterable of WorkflowEvent
        
    Returns:
        List of all events from the stream
    """
    return [event async for event in stream]

def _print_handoff_agent_user_request(response: AgentResponse) -> None:
    """Display the agent's response messages when requesting user input.

    This will happen when an agent generates a response that doesn't trigger
    a handoff, i.e., the agent is asking the user for more information.

    Args:
        response: The AgentResponse from the agent requesting user input
    """
    if not response.messages:
        raise RuntimeError("Cannot print agent responses: response has no messages.")

    print("\n[Agent is requesting your input...]")

    # Print agent responses
    for message in response.messages:
        if not message.text:
            # Skip messages without text (e.g., tool calls)
            continue
        speaker = message.author_name or message.role.value
        print(f"- {speaker}: {message.text}")

def handle_workflow_events(events: list[WorkflowEvent], verbose: bool = True) -> list[RequestInfoEvent]:
    """
    Process workflow events and extract any pending user input requests.
    
    This function inspects each event type and:
    - Prints workflow status changes (IDLE, IDLE_WITH_PENDING_REQUESTS, etc.)
    - Displays final conversation snapshots when workflow completes
    - Prints user input request prompts
    - Collects all RequestInfoEvent instances for response handling
    
    Args:
        events: List of WorkflowEvent to process
        verbose: Whether to print detailed status information
        
    Returns:
        List of RequestInfoEvent representing pending user input requests
    """
    requests: list[RequestInfoEvent] = []
    
    for event in events:
        # AgentRunEvent: Contains messages generated by agents during their turn
        if isinstance(event, AgentRunEvent):
            for message in event.data.messages:
                if not message.text:
                    # Skip messages without text (e.g., tool calls)
                    continue
                speaker = message.author_name or message.role.value
                print(f"- {speaker}: {message.text}")

        # HandoffSentEvent: Indicates a handoff has been initiated
        if isinstance(event, HandoffSentEvent):
            print(f"\n[Handoff from {event.source} to {event.target} initiated.]")

        # WorkflowStatusEvent: Indicates workflow state changes
        if isinstance(event, WorkflowStatusEvent) and event.state in {
            WorkflowRunState.IDLE,
            WorkflowRunState.IDLE_WITH_PENDING_REQUESTS,
        }:
            print(f"\n[Workflow Status] {event.state.name}")

        # WorkflowOutputEvent: Contains the final conversation when workflow terminates
        elif isinstance(event, WorkflowOutputEvent):
            conversation = cast(list[ChatMessage], event.data)
            if isinstance(conversation, list):
                print("\n=== Final Conversation Snapshot ===")
                for message in conversation:
                    speaker = message.author_name or message.role.value
                    print(f"- {speaker}: {message.text or [content.type for content in message.contents]}")
                print("===================================")

        # RequestInfoEvent: Workflow is requesting user input
        elif isinstance(event, RequestInfoEvent):
            if isinstance(event.data, HandoffAgentUserRequest):
                _print_handoff_agent_user_request(event.data.agent_response)
            requests.append(event)
    
    return requests
